# Copyright (C) Markus Franz Xaver Johannes Oberhumer

# see https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues
# see https://github.com/actions/stale

# Automatically closing issues is far from perfect, but then we only
# have limited resources and this approach favors issues that people
# actually care about.
#
# also see:
#   "Should I Stale or Should I Close? An Analysis of a Bot that Closes
#    Abandoned Issues and Pull Request".
#   https://igorwiese.com/images/papers/Paper_BotSE_19.pdf

name: ğŸ§ª GitHub - Close stale issues
on:
  schedule: [ cron: "50 0 * * 1" ] # run weekly Monday 00:50 UTC
  workflow_dispatch:
jobs:
  job-close-stale-issues:
    if: github.repository_owner == 'upx' && github.repository == 'upx/upx'
    name: Close stale issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          operations-per-run: 300
          exempt-all-milestones: true
          exempt-issue-labels: 'blocker,bug,enhancement,help wanted,regression'
          days-before-stale: 90
          days-before-close: 30
          stale-issue-message: |
            ### English
            This issue is stale because it has been open for 90 days with no activity. 
            Please remove the stale label or add a comment or this issue will be closed in 30 days.
            ### ä¸­æ–‡
            æ­¤é—®é¢˜å·²ç»æ‰“å¼€äº†90å¤©æ²¡æœ‰æ´»åŠ¨ï¼Œå› æ­¤å·²ç»è¿‡æ—¶ã€‚
            è¯·åˆ é™¤è¿‡æ—¶æ ‡ç­¾æˆ–æ·»åŠ è¯„è®ºï¼Œå¦åˆ™æ­¤é—®é¢˜å°†åœ¨30å¤©å†…å…³é—­ã€‚
          stale-pr-message: |
            ### English
            This PR is stale because it has been open for 90 days with no activity. 
            Please remove the stale label or add a comment or this PR will be closed in 30 days.
            ### ä¸­æ–‡
            æ­¤æ‹‰å–è¯·æ±‚å·²ç»æ‰“å¼€äº†90å¤©æ²¡æœ‰æ´»åŠ¨ï¼Œå› æ­¤å·²ç»è¿‡æ—¶ã€‚
            è¯·åˆ é™¤è¿‡æ—¶æ ‡ç­¾æˆ–æ·»åŠ è¯„è®ºï¼Œå¦åˆ™æ­¤æ‹‰å–è¯·æ±‚å°†åœ¨30å¤©å†…å…³é—­ã€‚
          close-issue-message: |
            ### English
            This issue was closed because it has been stale for 30 days with no activity. Please feel free to reopen.
            ### ä¸­æ–‡
            æ­¤é—®é¢˜å·²ç»è¿‡æ—¶30å¤©æ²¡æœ‰æ´»åŠ¨ï¼Œå› æ­¤å·²ç»å…³é—­ã€‚è¯·éšæ—¶é‡æ–°æ‰“å¼€ã€‚
          close-pr-message: |
            ### English
            This PR was closed because it has been stale for 30 days with no activity. Please feel free to reopen.
            ### ä¸­æ–‡
            æ­¤æ‹‰å–è¯·æ±‚å·²ç»è¿‡æ—¶30å¤©æ²¡æœ‰æ´»åŠ¨ï¼Œå› æ­¤å·²ç»å…³é—­ã€‚è¯·éšæ—¶é‡æ–°æ‰“å¼€.
          repo-token: ${{ secrets.GITHUB_TOKEN }}