name: ğŸ§ª CI Greetings

on: [ pull_request_target, issues ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello @${{ github.actor }} , thank you for submitting an issue!"
          pr-message: "Hello @${{ github.actor }} , thank you submitting a pull request!"
          issuesOpened: |
            ### English
            ğŸ‘‹ @{{ author }} Thank you for raising an issue.
            We will will investigate into the matter and get back to you as soon as possible.
            Please make sure you have given us as much context as possible.
            ### ä¸­æ–‡
            ğŸ‘‹ @{{ author }} æ„Ÿè°¢æ‚¨æå‡ºé—®é¢˜ã€‚
            æˆ‘ä»¬å°†è°ƒæŸ¥æ­¤é—®é¢˜å¹¶å°½å¿«å›å¤æ‚¨ã€‚
            è¯·ç¡®ä¿æ‚¨å°½å¯èƒ½æä¾›å°½å¯èƒ½å¤šçš„ä¸Šä¸‹æ–‡ã€‚
          
          pullRequestOpened: |
            ### English
            ğŸ‘‹ @{{ author }}
            Thank you for raising your pull request.
            Please make sure you have followed our contributing guidelines. We will review it as soon as possible.
            ### ä¸­æ–‡
            ğŸ‘‹ @{{ author }}
            æ„Ÿè°¢æ‚¨æå‡ºæ‹‰å–è¯·æ±‚ã€‚
            è¯·ç¡®ä¿æ‚¨å·²éµå¾ªæˆ‘ä»¬çš„è´¡çŒ®å‡†åˆ™ã€‚æˆ‘ä»¬å°†å°½å¿«å®¡æŸ¥å®ƒã€‚