name: ðŸ§ª CI Generate a list of contributors
on:
  push:
    branches:
      - main
jobs:
  contrib-readme-en-job:
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          image_size: 64
          readme_path: .github/README.md
          use_username: true
          commit_message: "ðŸ¤– [contrib-readme-action] : updated readme"
          committer_username: "Action Contrib Readme"
          committer_email: "xinansky99@gmail.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}